#docker-compose.yml
# https://docs.docker.com/compose/compose-file/compose-file-v3/


version: '3.9'

services:
  mssql-samples:
    container_name: mssql-server-samplesdb
    build:
      args:
        - INCLUDE_ALL_DATABASES=1 
      context: .
      dockerfile: DockerFile
    user: root
    ports:
      - "14330:1433"
    environment:
      - MSSQL_SA_PASSWORD=PaSSw0rd12#
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_DATA_DIR=/var/opt/mssql/data
      - MSSQL_LOG_DIR=/var/opt/mssql/log
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backup
    #volumes:
    #  - ${MSSQL_DATA_DIR}:/var/opt/mssql/data
    #  - ${MSSQL_LOG_DIR}:/var/opt/mssql/log
    #  - ${MSSQL_BACKUP_DIR}:/var/opt/mssql/backup
    networks:
      - compose_network
volumes:
  MSSQL_DATA_DIR:
  MSSQL_LOG_DIR:
  MSSQL_BACKUP_DIR:

networks:
  compose_network: