version: '3.9'

services:
  mssql-samples:
    container_name: mssql-server-samplesdb
    build: 
     context: .
     dockerfile: DockerFile
    ports: 
     - "14330:1433" 
    environment:
     MSSQL_SA_PASSWORD: "PaSSw0rd"
     ACCEPT_EULA: "Y"
     MSSQL_PID: "Developer"
     MSSQL_AGENT_ENABLED: "true"
     FORCE_ATTACH_IF_MDF_EXISTS: "${FORCE_ATTACH_IF_MDF_EXISTS}"
    volumes:
     - ${LOCAL_MOUNTPOINT}:/var/opt/mssql/data
     - ${SHARED_FOLDER}:/var/opt/mssql/SHARED_FOLDER
volumes:
  LOCAL_MOUNTPOINT:
  SHARED_FOLDER: